apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: eshop
  labels:
    app: product-service
  name: product-service
spec:
  ports:
  - port: 8014
    protocol: TCP
    targetPort: 8014
  selector:
    app: product-service
  type: NodePort
status:
  loadBalancer: {}
